import Head from "next/head";
import Link from "next/link";
import React from "react";
import TopPart from "../components/topPart";

import {
  Main,
  Bottom,
  List,
  TitleBox,
  Title,
  Icon,
} from "../components/sharedstyles";
import { AiOutlineUser } from "react-icons/ai";

interface Props {
  id: number;
  name: string;
  date: string;
  image: string;
}

export async function getStaticProps() {
  const res = await fetch("https://6524d386ea560a22a4ea24ca.mockapi.io/data1");
  const data = await res.json();
  return {
    props: {
      users: data.splice(0, 10),
    },
  };
}

const Users = ({ users }) => {
  return (
    <Main>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Title>Welocome to Dashboard</Title>

      <TopPart users={users} />
      <Bottom>
        <TitleBox>
          <span>Name</span>
          <span>Sign Up Date</span>
        </TitleBox>
        <ul>
          {users.map((item: Props) => {
            return (
              <Link href={`/users/${item.id}`}>
                <li key={item.id} style={{ listStyleType: "none" }}>
                  <Icon>
                    <AiOutlineUser size={25} style={{ color: "green" }} />
                  </Icon>
                  <List>
                    <span>{item.name}</span>

                    <span>{item.date.substring(0, 16)}</span>
                  </List>
                </li>
              </Link>
            );
          })}
        </ul>
      </Bottom>
    </Main>
  );
};

export default Users;
